'use client';

import React from 'react';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faShieldHalved, faServer, faUserSecret } from '@fortawesome/free-solid-svg-icons';
import { faGithub } from '@fortawesome/free-brands-svg-icons';

const PrivacyPage = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />

      <main className="flex-grow bg-[var(--color-background)] text-[var(--color-foreground)]">
        {/* Hero Section */}
        <div className="py-16 px-4 text-center bg-[var(--color-surface)]">
          <h1 className="text-4xl md:text-5xl font-bold font-orbitron mb-4">Privacy Policy</h1>
          <p className="text-[var(--color-text-muted)] max-w-2xl mx-auto">
            Effective Date: January 22, 2026
          </p>
        </div>

        {/* Content Container */}
        <div className="max-w-4xl mx-auto px-6 py-16 space-y-12">
          {/* 1. The Core Promise */}
          <section className="space-y-4">
            <div className="flex items-center gap-3 text-[var(--color-primary)]">
              <FontAwesomeIcon icon={faShieldHalved} className="text-2xl" />
              <h2 className="text-2xl font-bold font-orbitron">1. Our Core Promise</h2>
            </div>
            <p className="text-[var(--color-text-muted)] leading-relaxed">
              At One Buffalo Labs, we believe your personal growth data belongs to you, and only
              you. **Grit is a "Local-First" application.** This means that unlike traditional apps,
              we do not require you to create an account, and we do not store your challenge logs,
              journal entries, or photos on our proprietary servers.
            </p>
            <p className="text-[var(--color-text-muted)] leading-relaxed">
              The application logic is delivered to your device via{' '}
              <strong>Cloudflare Pages</strong>, but once loaded, the app runs entirely in your
              browser.
            </p>
          </section>

          {/* 2. Data Storage */}
          <section className="space-y-4">
            <div className="flex items-center gap-3 text-[var(--color-primary)]">
              <FontAwesomeIcon icon={faServer} className="text-2xl" />
              <h2 className="text-2xl font-bold font-orbitron">2. Data Storage</h2>
            </div>
            <p className="text-[var(--color-text-muted)] leading-relaxed">
              All data generated by Grit is stored locally on your specific device using an
              encrypted browser database technology called <strong>PouchDB</strong> (IndexedDB).
            </p>
            <ul className="list-disc pl-6 space-y-2 text-[var(--color-text-muted)]">
              <li>
                <strong>Challenge Data:</strong> Your daily tasks, progress, and failure logs never
                leave your device.
              </li>
              <li>
                <strong>Photos:</strong> If you use the progress photo feature, images are stored in
                your device's local storage. They are not uploaded to any cloud bucket.
              </li>
            </ul>
            <div className="bg-[var(--color-surface)]/50 p-4 rounded-lg border-l-4 border-[var(--color-primary)] text-sm text-[var(--color-text-muted)] mt-4">
              <strong>Note on Syncing:</strong> Because we do not store your data, Grit does not
              currently sync between devices. Data on your phone stays on your phone.
            </div>
          </section>

          {/* 3. Analytics (UPDATED) */}
          <section className="space-y-4">
            <div className="flex items-center gap-3 text-[var(--color-primary)]">
              <FontAwesomeIcon icon={faUserSecret} className="text-2xl" />
              <h2 className="text-2xl font-bold font-orbitron">3. Analytics & Third Parties</h2>
            </div>
            <p className="text-[var(--color-text-muted)] leading-relaxed">
              We use <strong>Google Analytics</strong> to collect anonymous usage statistics. This
              helps us understand how many people visit the site, which pages are most popular, and
              how we can improve the user experience.
            </p>
            <p className="text-[var(--color-text-muted)] leading-relaxed">
              Google Analytics may use cookies to track your session duration and general location
              (e.g., country or city). However, this data is{' '}
              <strong>aggregated and anonymous</strong>.
            </p>
            <p className="text-[var(--color-text-muted)] leading-relaxed font-bold">
              Google Analytics does NOT have access to your personal challenge data, your journal
              entries, or your progress photos.
            </p>
          </section>

          {/* 4. Your Right to Delete */}
          <section className="space-y-4">
            <h2 className="text-2xl font-bold font-orbitron text-[var(--color-foreground)]">
              4. Your Right to Delete
            </h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed">
              Since we do not hold your data, you do not need to ask us to delete it. You have total
              control:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-[var(--color-text-muted)]">
              <li>
                <strong>Reset Challenge:</strong> You can wipe your current challenge data instantly
                via the App Settings.
              </li>
              <li>
                <strong>Clear Browser Data:</strong> Clearing your browser's cache/site data for{' '}
                <code>grit.onebuffalolabs.com</code>
                will permanently erase all history from your device. Once deleted, this data cannot
                be recovered by us.
              </li>
            </ul>
          </section>

          {/* 5. Contact */}
          <section className="space-y-4 border-t border-[var(--color-surface)] pt-8">
            <h2 className="text-xl font-bold font-orbitron text-[var(--color-foreground)]">
              Questions & Support
            </h2>
            <p className="text-[var(--color-text-muted)] leading-relaxed">
              Since Grit is an open-source project, we handle all support and policy questions
              publicly on GitHub. This ensures transparency and helps other users with similar
              questions.
            </p>
            <a
              href="https://github.com/OneBuffaloLabs/grit/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-[var(--color-primary)] hover:text-[var(--color-foreground)] transition-colors font-bold">
              <FontAwesomeIcon icon={faGithub} />
              <span>Open an Issue on GitHub</span>
            </a>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default PrivacyPage;
